pipeline:
  # run install
  install:
    image: node
    commands:
      - yarn install --silent
    when:
      event: push

  # run lint
  lint:
    image: node
    commands:
      - yarn lint
    when:
      event: push

  # jest
  test:
    image: node
    commands:
      - yarn test
    when:
      event: push

  # release
  test:
    image: node
    commands:
      # NOTE: is a dry run - update to "release" to go live & publish
      - yarn release-dry
    when:
      event: push
      branch: [ master ]
