pipeline:
  # run install
  install:
    image: node
    commands:
      - yarn install --silent
    when:
      event: push

  # run lint
  lint:
    image: node
    commands:
      - yarn lint
    when:
      event: push

  # jest
  test:
    image: node
    commands:
      - yarn test
    when:
      event: push

  # release
  release:
    image: node
    commands:
      - yarn release
    environment:
      GITHUB_TOKEN: $${gh_token}
      NPM_TOKEN: $${npm_token}
    secrets: [ gh_token, npm_token ]
    when:
      event: push
      branch: [ master ]
