pipeline:
  # run install
  install:
    image: node
    commands:
      - yarn install --silent
    when:
      event: push

  # run lint
  lint:
    image: node
    commands:
      - yarn lint
    when:
      event: push

  # jest
  test:
    image: node
    commands:
      - yarn test
    when:
      event: push
