name: Version & Publish

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '<@OWNER>'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Autoscope package
        uses: khaazz/action-autoscope@master

      - name: Configure .npmrc
        run: echo "registry=https://npm.pkg.github.com/<OWNER>" >> ~/.npmrc

      - name: Install Dependencies
        run: yarn install

      - name: Bump version (patch)
        run: yarn version --patch --no-git-tag-version --no-commit-hooks

      - name: Build bundle
        run: yarn build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Commit version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: patch version" -a

      - name: Push version update
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
