name: Version & Publish

on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '<@OWNER>'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn install
      - name: Autoscope package
        uses: khaazz/action-autoscope@master
      - run: yarn version --patch
      - run: yarn build
      - name: Configure .npmrc
        run: echo registry=https://npm.pkg.github.com/<OWNER> >> .npmrc
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
