name: Version & Publish

on:
  push:
    branches:
      - master
jobs:
  # build bundle
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.0.0
      - run: yarn
      - run: yarn pkg-patch
      - run: yarn build

  # Publish package
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.0.0
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://npm.pkg.github.com
      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"
